refactor output of the script

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -2,11 +2,8 @@
 
 unset GIT_DIR
 
-NOCOLOR='\033[0m'
-RED='\033[1;31m'
-GREEN='\033[1;32m'
-WHITE='\033[1;37m'
-
+LINES=$(tput lines)
+COLUMNS=$(tput cols)
 OUTPUT_DIR=zuu
 BADGES_DIR=badges
 BADGES_STYLES=('plastic' 'flat' 'flatsquare' 'forthebadge' 'social')
@@ -33,6 +30,8 @@ TESTS_SUCCESS="${OUTPUT_DIR}/tests${SUCCESS_EXT}"
 TESTS_FAILURE="${OUTPUT_DIR}/tests${FAILURE_EXT}"
 CHECK_SUCCESS="${OUTPUT_DIR}/check${SUCCESS_EXT}"
 CHECK_FAILURE="${OUTPUT_DIR}/check${FAILURE_EXT}"
+FAILURE_TIME=20
+SUCCESS_TIME=5
 
 if [ -z "$1" ]
 then
@@ -43,6 +42,26 @@ then
 else
     GENERATE_BADGE=false
 fi
+
+function output {
+    local text="$2"
+    local b=""
+
+    for (( i = 0; i < (COLUMNS); i++ ))
+    do
+        b+="="
+    done
+    tput cuf 0
+    printf "\n%s\n" "$b"
+    printf "\n%*s\n" $(((${#1}+COLUMNS)/2)) "$1"
+    tput cuf 0
+    printf "\n%s\n\n" "$b"
+    cat "$3"
+    printf "\n%*s\n" $(((${#text}+COLUMNS)/2)) "$text"
+    read -r -s -t $4
+}
+
+
 
 function badge()
 {
@@ -99,7 +118,7 @@ else
     badge "audit" "${SUCCESS}"
 fi
 
-if ! cargo clippy --quiet -- -F keyword_idents -F warnings -F let-underscore -F rust-2018-compatibility -F rust-2018-idioms  -F rust-2021-compatibility -F future-incompatible -F unused -F unused_crate_dependencies -F unused_extern_crates  -D unused_macro_rules -F unused_results -F unused_qualifications -F nonstandard-style -F macro_use_extern_crate -F absolute_paths_not_starting_with_crate -F ambiguous_glob_imports -F clippy::all -F clippy::perf -F clippy::pedantic -F clippy::style -F clippy::suspicious -F clippy::correctness -F clippy::nursery -F clippy::complexity -F clippy::cargo > ${CLIPPY_SUCCESS} 2> ${CLIPPY_FAILURE}
+if ! cargo clippy -- -F keyword_idents -F warnings -F let-underscore -F rust-2018-compatibility -F rust-2018-idioms  -F rust-2021-compatibility -F future-incompatible -F unused -F unused_crate_dependencies -F unused_extern_crates  -D unused_macro_rules -F unused_results -F unused_qualifications -F nonstandard-style -F macro_use_extern_crate -F absolute_paths_not_starting_with_crate -F ambiguous_glob_imports -F clippy::all -F clippy::perf -F clippy::pedantic -F clippy::style -F clippy::suspicious -F clippy::correctness -F clippy::nursery -F clippy::complexity -F clippy::cargo > ${CLIPPY_SUCCESS} 2> ${CLIPPY_FAILURE}
 then
     CLIPPY=false
     badge "clippy" "${FAILURE}"
@@ -110,7 +129,7 @@ fi
 
 if ! cargo test  > ${TESTS_SUCCESS} 2> ${TESTS_FAILURE}
 then
-    TESTS=fals
+    TESTS=false
     badge "test" "${FAILURE}"
 else
     TESTS=true
@@ -132,51 +151,54 @@ clear
 
 if [ ${VERIFY} == true ]
 then
-    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] verify${NOCOLOR}"
+    output "Project valid" "waiting ${SUCCESS_TIME} secs" "${VERIFY_SUCCESS}" ${SUCCESS_TIME}
 else
-    cat "${VERIFY_FAILURE}"
+    output "Project not valid" "waiting ${FAILURE_TIME} secs" "${VERIFY_FAILURE}" ${FAILURE_TIME}
 fi
 
 if [ ${FORMAT} == true ]
 then
-    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] format${NOCOLOR}"
+    output "Code format valid"  "waiting ${SUCCESS_TIME} secs" "${FORMAT_SUCCESS}" ${SUCCESS_TIME}
 else
-   cat "${FORMAT_FAILURE}"
+    output "Code format error" "waiting ${FAILURE_TIME} secs" "${FORMAT_FAILURE}" ${FAILURE_TIME}
 fi
 
 if [ ${AUDIT} == true ]
 then
-    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] audit${NOCOLOR}"
+    output "Audit passes check" "waiting ${SUCCESS_TIME} secs" "${AUDIT_SUCCESS}" ${SUCCESS_TIME}
 else
-    cat "${AUDIT_FAILURE}"
+    output "Audit detect warnings" "waiting ${FAILURE_TIME} secs" "${AUDIT_FAILURE}" ${FAILURE_TIME}
 fi
 
 if [ ${CLIPPY} == true ]
 then
-    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] clippy${NOCOLOR}"
+    output "Code is clean" "waiting ${SUCCESS_TIME} secs" "${CLIPPY_SUCCESS}" ${SUCCESS_TIME}
 else
-    cat "${CLIPPY_FAILURE}"
+    output "Code contains errors" "waiting ${FAILURE_TIME} secs" "${CLIPPY_FAILURE}" ${FAILURE_TIME}
 fi
 
 if [ ${TESTS} == true ]
 then
-    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] tests${NOCOLOR}"
+    output "Test passes" "waiting ${SUCCESS_TIME} secs" "${TESTS_SUCCESS}" ${SUCCESS_TIME}
 else
-   cat "${TESTS_FAILURE}"
+    output "Tests has failure" "waiting ${FAILURE_TIME} secs" "${TESTS_FAILURE}" ${FAILURE_TIME}
 fi
 
 if [ ${CHECK} == true ]
 then
-    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] check${NOCOLOR}"
+    output "Code clean" "waiting ${SUCCESS_TIME} secs" "${CHECK_SUCCESS}" ${SUCCESS_TIME}
 else
-    cat "${CHECK_FAILURE}"
+    output "Code contains errors" "waiting ${FAILURE_TIME} secs" "${CHECK_FAILURE}" ${FAILURE_TIME}
 fi
-
 
 if [ ${FORMAT} == true ] && [ ${VERIFY} == true ] && [ ${AUDIT} == true ] && [ ${CLIPPY} == true ]  && [ ${TESTS} == true ] && [ ${CHECK} == true ]
 then
-    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] Code is valid${NOCOLOR}\n"
+    tput clear
+    title="The code can be committed"
+    printf "\n%*s\n" $(((${#title}+COLUMNS)/2)) "$title"
     exit 0
 else
+      title="The code is not valid"
+      printf "\n%*s\n" $(((${#title}+COLUMNS)/2)) "$title"
     exit 1
 fi
