fix script bug

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,11 +1,13 @@
 #!/usr/bin/bash
 
 unset GIT_DIR
+
 NOCOLOR='\033[0m'
 RED='\033[1;31m'
 GREEN='\033[1;32m'
 WHITE='\033[1;37m'
 
+OUTPUT_DIR=zuu
 FORMAT=false
 VERIFY=false
 AUDIT=false
@@ -13,14 +15,21 @@ CLIPPY=false
 TESTS=false
 CHECK=false
 
-if ! cargo verify-project --quiet  > verify.out 2> verify_error.out
+if [ ! -d ${OUTPUT_DIR} ]
+then
+    mkdir ${OUTPUT_DIR}
+    touch "${OUTPUT_DIR}/.gitignore"
+    echo "*.out" > "${OUTPUT_DIR}/.gitignore"
+fi
+
+if ! cargo verify-project --quiet  > "${OUTPUT_DIR}/verify.out" 2> "${OUTPUT_DIR}/verify_error.out"
 then
     VERIFY=false
 else
     VERIFY=true
 fi
 
-if ! cargo fmt --check  > fmt.out 2> fmt_error.out
+if ! cargo fmt --check  > "${OUTPUT_DIR}/fmt.out" 2> "${OUTPUT_DIR}/fmt_error.out"
 then
     FORMAT=false
 else
@@ -28,28 +37,28 @@ else
 fi
 
 
-if ! cargo audit --quiet  > audit.out 2> audit_error.out
+if ! cargo audit --quiet  > "${OUTPUT_DIR}/audit.out" 2> "${OUTPUT_DIR}/audit_error.out"
 then
     AUDIT=false
 else
     AUDIT=true
 fi
 
-if ! cargo clippy --quiet -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo > clippy.out 2> clippy_error.out
+if ! cargo clippy --quiet -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo > "${OUTPUT_DIR}/clippy.out" 2> "${OUTPUT_DIR}/clippy_error.out"
 then
     CLIPPY=false
 else
     CLIPPY=true
 fi
 
-if ! cargo test --quiet --tests --all-targets --no-fail-fast  > tests.out 2> test_error.out
+if ! cargo test --quiet --tests --all-targets --no-fail-fast  > "${OUTPUT_DIR}/tests.out" 2> "${OUTPUT_DIR}/tests_error.out"
 then
     TESTS=false
 else
     TESTS=true
 fi
 
-if ! cargo check --quiet --all-targets  > check.out 2> check_error.out
+if ! cargo check --quiet --all-targets  > "${OUTPUT_DIR}/check.out" 2> "${OUTPUT_DIR}/check_error.out"
 then
     CHECK=false
 else
@@ -60,14 +69,14 @@ fi
 clear
 
 
-if [ $VERIFY == true ]
+if [ ${VERIFY} == true ]
 then
     echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] verify${NOCOLOR}"
 else
     echo -e "\n${WHITE}[${RED} KO${WHITE} ] verify${NOCOLOR}"
 fi
 
-if [ $FORMAT == true ]
+if [ ${FORMAT} == true ]
 then
     echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] format${NOCOLOR}"
 else
@@ -75,35 +84,36 @@ else
 fi
 
 
-if [ $AUDIT == true ]
+if [ ${AUDIT} == true ]
 then
     echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] audit${NOCOLOR}"
 else
     echo -e "\n${WHITE}[${RED} KO${WHITE} ] audit${NOCOLOR}"
 fi
 
-if [ $CLIPPY == true ]
+if [ ${CLIPPY} == true ]
 then
     echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] clippy${NOCOLOR}"
 else
     echo -e "\n${WHITE}[${RED} KO${WHITE} ] clippy${NOCOLOR}"
 fi
 
-if [ $TESTS == true ]
+if [ ${TESTS} == true ]
 then
     echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] tests${NOCOLOR}"
 else
     echo -e "\n${WHITE}[${RED} KO${WHITE} ] tests${NOCOLOR}"
 fi
 
-if [ $CHECK == true ]
+if [ ${CHECK} == true ]
 then
     echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] check${NOCOLOR}"
 else
     echo -e "\n${WHITE}[${RED} KO${WHITE} ] check${NOCOLOR}"
 fi
 
-if test $CLIPPY && $TESTS && $CHECK && $AUDIT && $VERIFY && $FORMAT
+
+if [ ${FORMAT} == true ] && [ ${VERIFY} == true ] && [ ${AUDIT} == true ] && [ ${CLIPPY} == true ]  && [ ${TESTS} == true ] && [ ${CHECK} == true ]
 then
     echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] Code is valid${NOCOLOR}\n"
     exit 0
